### PR TITLE
Feature/RR-844 Integrate File Service

### PR DESCRIPTION
**Pull request by sirctseb**
#### What's this PR do?
Replaces the command line zip and aws sdk upload with a call to the new file service (https://github.com/amida-tech/file-repository-service).

#### Related JIRA tickets:
[RR-841](https://jira.amida-tech.com/browse/RR-844)

#### How should this be manually tested?
1. Run an instance of the file repository service with valid aws credentials (https://github.com/amida-tech/file-repository-service/blob/master/README.md)
1. Ensure that the .env file contains a
  - `FILE_SERVICE_BASE_URL` which points to the file service instance domain (e.g. http://localhost:8080), and
  - `RECREG_COHORT_BUCKET` with the bucket that the file service instance is uploading to.
1. Check that tests pass (except those two federated search tests that have been failing for a while
1. Run the backend and frontend
1. Log in as a clinician and create and resend a cohort file
1. Check that the zipped cohort file is uploaded to your s3 and that it unzips with the displayed password.

#### Screenshots (if appropriate):

### CODE REVIEW

**Comment by unprofessional** [comment]
I performed an initial functional test and this appears to work for me. I will try to get @Arghast set up for his series of robustness testing later on and then do a code review so this can be merged.

**Comment by unprofessional** [comment]
@jsachs -- we will need to discuss deployment setup for the dependency repo needed for this @ https://github.com/amida-tech/file-repository-service/blob/master/README.md)

**Comment by jsachs** [comment]
@unprofessional do you know if there will be HIPAA passthrough for the file service? If so, it will have to be an additional Aptible container. Otherwise, we can make it a tiny AWS AMI.

**Comment by unprofessional** [comment]
@mhiner can you weigh in on Jacob's question above?

**Comment by unprofessional** [comment]
Mike approves of an Aptible deployment.

**Comment by jsachs** [comment]
@unprofessional I think @sirctseb said it was working just fine, although there was one recreg-related bug.

**Comment by Arghast** [comment]
@unprofessional @sirctseb Functionality looks good on this.

**Pull request merged**
