### PR TITLE
Feature/rr 852

### PR DESCRIPTION
**Pull request by au2**
If this PR fixes a bug, you _must_ add test cases representative of the bug.

Please refer to [Tettra](https://app.tettra.co/teams/amida/pages/amida-pull-request-and-code-review-guide) for PR review guidelines.

#### How should this be manually tested?

1) Post a survey.
2) Get the posted survey from server.
3) Change various fields to create a patch but leave all fields that need to be the same as is. Also add a 'complete: true' to top level. That is for backward compatibility.
4) Remove survey 'id' from patch and call surveys/{id} [PATCH] with the patch object.
5) Check if the fields are changed as expected.

### CODE REVIEW

**Comment by unprofessional** [comment]
Assigning @Arghast for testing (with my current client branch) to determine scenarios that need addressing/fixing.

**Comment by Arghast** [comment]
@au2 @unprofessional User can only add edit and delete survey conditions before saving a survey for the first time. After saving the survey, user is unable to configure survey conditions in any way.

I will test conditional questions today.

**Comment by unprofessional** [comment]
@au2 To clarify, adding/removing Survey Conditions when PATCHing does not seem to do anything at all.

Here's the JSON exchange.

Initial POST to create newSurvey:
```
{
	"name": "Conditionals-50",
	"description": "dsfgdfsgdsf",
	"questions": [
		{
			"required": false,
			"text": "Sample Boolean",
			"type": "bool"
		}
	],
	"status": "draft",
	"enableWhen": [
		{
			"answer": {
				"boolValue": true
			},
			"surveyId": 9,
			"questionId": 22,
			"logic": "equals"
		},
		{
			"answer": {
				"choice": 15
			},
			"surveyId": 2,
			"questionId": 8,
			"logic": "equals"
		}
	]
}
```
----------
GET survey:
```

	"id": 41,
	"status": "draft",
	"authorId": 1,
	"name": "Conditionals-50",
	"description": "dsfgdfsgdsf",
	"enableWhen": [
		{
			"id": 60,
			"logic": "equals",
			"questionId": 22,
			"surveyId": 9,
			"answer": {
				"boolValue": true
			}
		},
		{
			"id": 61,
			"logic": "equals",
			"questionId": 8,
			"surveyId": 2,
			"answer": {
				"choice": 15
			}
		}
	],
	"questions": [
		{
			"id": 87,
			"type": "bool",
			"isIdentifying": false,
			"common": false,
			"text": "Sample Boolean",
			"required": false
		}
	]
}
```
-----------
PATCH after adding new enableWhen rule (for Survey):
```
{
	"questions": [
		{
			"id": 87,
			"type": "bool",
			"isIdentifying": false,
			"common": false,
			"text": "Sample Boolean",
			"required": false
		}
	],
	"status": "draft",
	"enableWhen": [
		{
			"id": 60,
			"logic": "equals",
			"questionId": 22,
			"surveyId": 9,
			"answer": {
				"boolValue": true
			}
		},
		{
			"id": 61,
			"logic": "equals",
			"questionId": 8,
			"surveyId": 2,
			"answer": {
				"choice": 15
			}
		},
		{
			"answer": {
				"boolValue": true
			},
			"surveyId": 2,
			"questionId": 5,
			"logic": "equals"
		}
	],
	"name": "Conditionals-50",
	"description": "dsfgdfsgdsf",
	"forceQuestions": true
}
```
-------------
GET survey:
```
{
	"id": 41,
	"status": "draft",
	"authorId": 1,
	"name": "Conditionals-50",
	"description": "dsfgdfsgdsf",
	"enableWhen": [
		{
			"id": 60,
			"logic": "equals",
			"questionId": 22,
			"surveyId": 9,
			"answer": {
				"boolValue": true
			}
		},
		{
			"id": 61,
			"logic": "equals",
			"questionId": 8,
			"surveyId": 2,
			"answer": {
				"choice": 15
			}
		}
	],
	"questions": [
		{
			"id": 87,
			"type": "bool",
			"isIdentifying": false,
			"common": false,
			"text": "Sample Boolean",
			"required": false
		}
	]
}
```

Note how our added condition wasn't added. The same things occurs if we try to delete the SurveyCondition via PATCH (by removing the condition from the enableWhen list).

**Comment by au2** [comment]
@unprofessional you need to add 'complete: true' to the patch JSON object.  I wanted to remain backwards compatible with the older version without complete. I am not sure what this outside mobile application is doing and I think Indaba starting to use the old patch version.

**Comment by unprofessional** [comment]
It appears that an admin can no longer update a Question's description (`instruction`) when PATCHing a Survey.
Error shows up as: `Cannot match against 'undefined' or 'null'.`

**Comment by au2** [comment]
Cannot match against 'undefined' or 'null'. should be fixed now.  I also updated sequelize (the version RR using was the beta version) and did the required changes in RR code.  You need to update your node_modules.  Maybe we should start using yarn for this repo as well.

**Comment by unprofessional** [comment]
NOTE: Afsin and I spoke about addressing an issue related to PATCH `choice.id` when in use for Question Conditions

**Pull request merged**
